package rules.price;

import com.ftn.sbnz.model.models.MenuItem;
import com.ftn.sbnz.model.models.Order;
import com.ftn.sbnz.model.models.Charge;

dialect  "mvel"

rule "Calculate Order Price"
    lock-on-active true
    when
        $order: Order($items: items, $distance: deliveryDistance, $discount: customer.getDiscount())
        accumulate(
            MenuItem($price: price) from $items,
            $totalItemPrice: sum($price)
        )
    then
        Charge charge = new Charge();
        charge.setProductsCost($totalItemPrice);
        charge.setServicesFee(0.5);
        charge.setDeliveryFee($distance * 1.1);
        charge.setUserDiscount($discount);
        charge.setDiscountValue($totalItemPrice * $discount);
        charge.setTotal($totalItemPrice - charge.getDiscountValue() + charge.getDeliveryFee() + charge.getServicesFee());
        modify($order){setCharge(charge)}
end
