spring:
  datasource:
    password: sbnz
    username: sbnz
    url: jdbc:h2:file:./data/delivery-app;AUTO_SERVER=true;
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop